project:
  type: book
  output-dir: "."

book:
  title: "CASA0023 Remote Sensing - Learning Diary"
  author: "Paul McNicholas"
  date: "01/21/2025"
  chapters:
    - index.qmd
    - 1_intro.qmd
    - 2_portfolio.qmd
    - 2_xarigan_pres.html
    - 3_data_corrections.qmd
    - 4_policy_applications.qmd
    - 5_google_earth_engine.qmd
    - 6_classification_I.qmd
    - references.qmd
  reader-mode: true

bibliography: 
  - references.bib

format:
  html:
    theme: cosmo
    lightbox: true
    word-count: true
  pdf:
    documentclass: scrreprt

editor: visual

