project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 Remote Sensing - Learning Diary"
  author: "Paul McNicholas"
  date: "01/21/2025"
  chapters:
    - index.qmd
    - intro.qmd
#    - 2_portfolio.qmd
#    - 3_Data_Corrections.qmd
    - references.qmd
  reader-mode: true

bibliography: 
  - references.bib
#  - pleiades_references.bib

format:
  html:
    theme: cosmo
    lightbox: true
  pdf:
    documentclass: scrreprt

editor: visual

